name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pull the repo code into the Actions runner
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Login to Docker Hub using the secrets we stored
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Set up Buildx (needed for building Docker images in Actions)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Build and push image to Docker Hub
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/task-manager-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/task-manager-api:${{ github.sha }}
